### Site info.
title: 万东波的表空间
tagline: DB 爱好者
author: David Wan
email: wandongbo@126.com
description: DBA
keywords: "Reading, Muisc, 历史，文学, 互联网, 区块链"
url: "https://dbathread.com" # The base hostname & protocol for your site
enforce_ssl: "dbathread.com" # The base hostname & protocol for your site
locale: en_US
encoding: UTF-8

### Personal info and site tools info.
twitter_username: 
github_username: swordstick 
favicon:     "/images/favicon.ico"
aboutme: DBA 爱好者
aboutme_photo: "/images/wentasy.png"
google_analytics_key: 

### Site settings.
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True.
default_column: "one" # Blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # Blog sidebar language set, only include: English(en), Chinese (cn), Japanese (jp), Polish (pl) and Korean(kr).
path: "/_data/comments" # Path which stored comments etc.

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Google_Search: "Google Search"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      WechatDBTalk: "Official WeChat"
      WechatDonate: "Donate"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "Blogroll"
      Categories: "分类目录"
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Google_Search: "搜索"
      Tags: "标签"
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      WechatDBTalk: "微信公众号"
      WechatDonate: "微信捐赠"
    jp:
      Aboutme: " 著者 "
      Archives: " アーカイブ "
      Blogroll: " ブログロール "
      Categories: " カテゴリー "
      Copyright_Notice: " 著作権表示 "
      Recent_Posts: " 最近の投稿 "
      Tags: " タグ "
      Previous: " 前の記事 "
      Next: " 次の記事 "
      PostedInCategories: " カテゴリー："
      Taggedwith: "| タグ："
      PostDate: "| 投稿日時: "
      Google_search: " サイト内検索 "
      Home: " ホーム "
      About: " このブログについて "
      Guestbook: " メッセージ "
      Subscribe: " 購読 "
    pl:
      Aboutme: "O mnie"
      Archives: "Archiwum"
      Blogroll: "Odnośniki"
      Categories: "Kategorie"
      Copyright_Notice: "Prawa autorskie"
      Recent_Posts: "Najnowsze wpisy"
      Tags: "Tagi"
      Previous: "Starsze"
      Next: "Nowsze"
      PostedInCategories: "Kategoria"
      Taggedwith: "tagi"
      PostDate: "on "
      Google_search: "Wyszukiwarka"
      Home: "Strona główna"
      About: "O mnie"
      Guestbook: "Księga gości"
      Subscribe: "Subskrypcja"

### Build settings.
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
excerpt_separator: <!--more-->

### Kramdown settings.
kramdown:
  input: GFM
  hard_wrap: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  syntax_highlighter: rouge

### Custom gems.
